//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto2021.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class cliente
    {
        public int id { get; set; }

        [Required(ErrorMessage = "El nombre no puede ir vacio")]
        [StringLength(20, ErrorMessage = "Usted supero el limite de 20 caracteres")]
        public string nombre { get; set; }
        public string documento { get; set; }
        public string email { get; set; }
    }
}
