//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto2021.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class usuario
    {
        public int id { get; set; }

        [Required (ErrorMessage="El nombre no puede ir vacio")]
        [StringLength(20, ErrorMessage ="Usted supero el limite de 20 caracteres")]
        public string nombre { get; set; }
        public string apellido { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }

        [EmailAddress]
        public string email { get; set; }

        
        public string password { get; set; }
    }
}
